- hosts: all
  gather_facts: no
  pre_tasks:
  - name: install Python as Ansible prerequisite
    raw: test -e /usr/bin/python || apt-get -y install python
    register: output
    changed_when: output.stdout.strip() != ""

  tasks:
  - name: install system updates
    apt:
      upgrade: dist
  - name: install `webhook`
    apt:
      name: webhook

