provider "scaleway" {
  /* Using .scwrc for auth. Because `scw` is needed
     to see available images anyway

  organization = "${var.scaleway_organization}"
  token        = "${var.scaleway_token}"
*/
  region = "ams1"
}

data "scaleway_image" "bionic" {
  architecture = "arm64"
  name         = "Ubuntu Bionic"
}

resource "scaleway_server" "xe3" {
  name = "xe3"

  // Using Ubuntu 18.04 LTS (Bionic)
  // https://community.scaleway.com/t/list-of-image-uuids-without-api/7672/2

  image = data.scaleway_image.bionic.id
  type  = "ARM64-2GB"
}

resource "scaleway_ip" "xe3ip" {
  server = scaleway_server.xe3.id
}

// Produce Ansible inventory file with bot server IP

data "template_file" "inventory" {
  template = <<-EOT
# Ansible inventory is generated by Terraform
root@${scaleway_server.xe3.public_ip}
EOT

  depends_on = [scaleway_ip.xe3ip]
}

resource "null_resource" "generate_inventory" {
  triggers = {
    template_rendered = "${data.template_file.inventory.rendered}"
  }

  provisioner "local-exec" {
    command = "echo '${data.template_file.inventory.rendered}' > inventory"
  }
}

